### ISSUE TITLE
Unable to render Card preview

### ISSUE THREAD

**Issue by jiyuujin** [jiyuujin/ohayo-website#7]
Unable to render Card preview at https://ohayo.nekohack.me/
Also unable to render Card preview of the base URL, https://vitesse.netlify.app/

**Comment by elzup** [comment]
suggestion

```diff
-        npm run build --if-present
+        npm run build:ssg --if-present
```

https://github.com/jiyuujin/ohayo-website/blob/f388dc1105b91a98f8a36be9a9181491a26a87fd/.github/workflows/nodejs.yml#L43

**Comment by jiyuujin** [comment]
layouts, pages を設定すると上手く反映できました

<img width="1031" alt="スクリーンショット 2021-11-03 13 02 55" src="https://user-images.githubusercontent.com/9650581/140008527-d37520ab-f9c9-4915-ab5f-edd7f0afacbf.png">
